import userRoute from "./components/user/userRoutes";
import adminRoute from "./components/admin/admin.routes";
// import productRouters from "./components/products/productRouters";
import deliveryRoutes from "./components/delivery/deliveryRoutes";
import supplierRouters from "./components/supplier/supplierRouters";
import brandRouter from "./components/brands/brandRouter";
import cateRouter from "./components/category/categoryRouters";
import productRouters from "./components/product/productRouters";
import auctionRoutes from "./components/auction/auctionRoutes";
import bankRoutes from "./components/bank/bankRoutes";
import notifyRoutes from "./components/notification/notifyRoutes";
import buyBankRoutes from "./components/bank/buyBidRoutes";
import tradeoutRoute from "./components/tradeExchange/tradeoutRoute";
import transferRoutes from "./components/bank/transferRoutes";
import reportRoute from "./components/reports/depositRoute";
// import paymentRoutes from "./components/bank/paymentRoutes";
import couponRoutes from "./components/coupon/couponRoutes";
import permissionRoutes from './components/permission/permissionRoutes';
import settingRoutes from "./components/settings/settingRoutes";
import reviewRoute from "./components/review/packageRoute";
import reviewPackageRoute from "./components/review/packagePermissionRoute";
import reviewManagementRoute from "./components/review/reviewManagementRoute";
import employeeRoute from "./components/employee/employeeRoutes";
import typeRoutes from "./components/notification/typeRoute";
import logsRoutes from "./components/log/logRoute";
import userFeedbackRoute from "./components/review/userFeedbackRoute";
const userString = "/user";
const adminString = "/admin";
const auctionString = "/auction";
const reportString = "/reports";
// const productString = "/products";
const exclString = "/delivery";
const tradeoutString = "/tradeout";
const supplierString = "/supplier";
const brandString = "/brands";
const cateString = "/category";
const productsString = "/products";
const bankStrings = "/bank";
const notifyStrings = "/notify";
const buyBankString = "/buybank";
const transferString = "/transfer";
const paymentString = "/payment";
const type = "/type";
const coupon = '/coupon';
const permission = '/permission';
const reviewString = "/review";
const reviewPackageString = '/reviewpermission';
const settingString = '/setting';
const reviewManagementString = '/managementReview';
const employeeString = "/employee";
const logsString = "/logs";
// export default ( app: any ) => {
// app.use( userRoute);}
export default (app: any) => {
        app.use(userString, userRoute);
        app.use(adminString, adminRoute);
        app.use(auctionString, auctionRoutes);
        app.use(settingString, settingRoutes);
        app.use(exclString, deliveryRoutes);
        app.use(supplierString, supplierRouters);
        app.use(brandString, brandRouter);
        app.use(cateString, cateRouter);
        app.use(productsString, productRouters);
        app.use(bankStrings, bankRoutes);
        app.use(notifyStrings, notifyRoutes);
        app.use(buyBankString, buyBankRoutes);
        app.use(transferString, transferRoutes);
        app.use(tradeoutString, tradeoutRoute);
        app.use(type, typeRoutes);
        // app.use(paymentString, paymentRoutes);
        app.use(coupon, couponRoutes);
        app.use(permission, permissionRoutes);
        app.use(reviewString, reviewRoute);
        app.use(reviewPackageString, reviewPackageRoute);
        app.use(reviewManagementString, reviewManagementRoute);
        app.use(reviewManagementString, userFeedbackRoute);
        // app.use(tradeoutString, tradeoutRoute);
        app.use(employeeString, employeeRoute);
        app.use(reportString, reportRoute);
        app.use(logsString, logsRoutes);
        // app.use( appointmentString, appointmentRoute);
        // app.use( consultancyString, consultancyRoute);
        // app.use( diagnosticString, diagnosticRoute);
        // app.use( doctorString, doctorRoute);
        // app.use( homeAppointmentString, homeAppointmentRoute);
        // app.use( nursingString, nursingRoute);
        // app.use( pharmacyString, pharmacyRoute);
        // app.use( reportString, reportRoute);
        // app.use( supportString, supportRoute);
        // app.use( logString, logRoute);
        // app.use( settingString, settingRoute);
        // app.use( notificationString, notificationRoute);
};
